export const GET_TASKS = 'GET_SUBSCRIBER';
export const TASKS_RECEIVED = 'TASKS_RECEIVED';

export const CREATE_TASK = 'CREATE_TASK';
export const TASK_CREATED = 'TASK_CREATED';

export const UPDATE_TASK = 'UPDATE_TASK';
export const TASK_UPDATED = 'TASK_UPDATED';

export const DELETE_TASK = 'DELETE_TASK';
export const TASK_DELETED = 'TASK_DELETED';

export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';
export const FILTER_TASKS = 'FILTER_TASKS';
